# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('balance', models.PositiveIntegerField(verbose_name='Current balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_friendly_id', models.UUIDField(editable=False, unique=True)),
                ('created', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('delta', models.IntegerField(help_text='Balance delta.')),
                ('reference', models.TextField(blank=True)),
                ('reference_type', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('NONE', 'None')], default='NONE', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('debug_balance', models.IntegerField(help_text='Balance after action')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('user', models.ForeignKey(help_text='User on make an action', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account action',
                'verbose_name_plural': 'Account actions',
            },
        ),
    ]
