# Generated by Django 2.0.2 on 2018-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180324_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default='0', verbose_name='Current balance'),
        ),
    ]
