# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180701_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited'), ('WITHDRAWN', 'Withdrawn')], default='NONE', max_length=30),
        ),
    ]
