# Generated by Django 4.2.3 on 2023-07-10 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20210704_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeysPerformanceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expenses_by_category', models.JSONField(default=dict, help_text='Expenses by category')),
                ('daily_data', models.JSONField(default=dict, help_text='Daily data')),
                ('monthly_data', models.JSONField(default=dict, help_text='Monthly data')),
            ],
            options={
                'verbose_name': 'Keys Performance Indicator',
                'verbose_name_plural': 'Keys Performance Indicators',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products_ids', models.ManyToManyField(blank=True, related_name='products', to='api.product')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='api.transaction'),
        ),
    ]
