# Generated by Django 4.2.3 on 2023-07-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_keysperformanceindicator_product_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['amount'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
